name: Even handlers
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  event-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Events log
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: action/checkout@v6
      - name: Install node
        uses: action/setup-node@v6
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
