name: Reusable use main
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Cache dependencies
        id: caching
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-dependencies-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.caching.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install npm
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Cache dependencies
        id: caching
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-dependencies-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.caching.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run test
        id: test-app
        run: npm run test
      - name: Upload test report
        if: failure() && steps.test-app.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install npm
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Cache dependencies
        id: caching
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-dependencies-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.caching.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Upload arifact files
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: dist

  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      input_data_name: build-file

  report:
    needs: [lint-check, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Generating report
        run: echo "Generate report..."